version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci

  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    labels:
      - dependencies
      - npm

  - package-ecosystem: cargo
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust
