# Dependency Review blocks vulnerable dependency changes before they land in PRs.
# Keep this config conservative for public OSS: fail only high/critical severity,
# allow permissive licenses, and keep summaries visible to reviewers.
fail-on-severity: high
comment-summary-in-pr: on-failure
allow-licenses:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MIT
  - MPL-2.0
  - Unicode-3.0
  - Zlib
