use super::{ClientInstallKind, ClientInstallSupport, ClientTarget, JsonMcpServerShape};

pub const CLIENT_TARGETS: &[ClientTarget] = &[
    ClientTarget {
        id: "codex",
        family_id: "codex",
        display_name: "OpenAI Codex",
        aliases: &["codex-cli", "openai-codex"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-cli-ide",
        proof_tier: "tier-1",
        config_format: "toml",
        config_paths: &["~/.codex/config.toml", ".codex/config.toml"],
        config_precedence: &["project-trusted", "user"],
        native_scopes: &["user", "project"],
        supported_ingresses: &["stdio", "streamable-http"],
        documented_features: &["tools", "oauth"],
        documented_constraints: &["shared-config-cli-ide"],
        notes: &[
            "CLI and IDE extension share the same config layers.",
            "Project config applies only in trusted projects.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::TomlMcpServersManagedTable,
            preferred_scope: "user",
            preferred_config_path: "~/.codex/config.toml",
        }),
    },
    ClientTarget {
        id: "claude-code",
        family_id: "claude",
        display_name: "Anthropic Claude Code",
        aliases: &["claude", "claude code", "claudecode"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-cli-ide-web",
        proof_tier: "tier-1",
        config_format: "json",
        config_paths: &["~/.claude.json", ".mcp.json"],
        config_precedence: &["project", "user", "local"],
        native_scopes: &["local", "project", "user"],
        supported_ingresses: &["stdio", "streamable-http", "sse"],
        documented_features: &["tools", "oauth"],
        documented_constraints: &["sse-deprecated", "managed-config"],
        notes: &[
            "Project-scoped servers live in .mcp.json.",
            "Local and user-scoped servers live in ~/.claude.json.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "mcpServers",
                url_field: "url",
                include_type_http: true,
                include_tools_star: false,
                include_disabled_false: false,
            }),
            preferred_scope: "user",
            preferred_config_path: "~/.claude.json",
        }),
    },
    ClientTarget {
        id: "claude-api-connector",
        family_id: "claude",
        display_name: "Anthropic Claude API MCP connector",
        aliases: &["claude-api", "anthropic-mcp-connector", "claude-mcp-connector"],
        maturity: "documented",
        surface_class: "cloud",
        surface_kind: "cloud-api-connector",
        proof_tier: "catalog-only",
        config_format: "api-request",
        config_paths: &[],
        config_precedence: &["request"],
        native_scopes: &["request"],
        supported_ingresses: &["streamable-http", "sse"],
        documented_features: &["tools", "oauth"],
        documented_constraints: &["tools-only", "public-http-only", "beta-header-required"],
        notes: &[
            "Only tool calls are supported on this surface.",
            "The server must be publicly reachable over HTTP; local stdio is not supported.",
        ],
        install_support: None,
    },
    ClientTarget {
        id: "vscode-workspace",
        family_id: "vscode",
        display_name: "Visual Studio Code user configuration",
        aliases: &[
            "vscode",
            "vscode-user",
            "vs-code",
            "code",
            "visual-studio-code",
        ],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-editor",
        proof_tier: "tier-1",
        config_format: "json",
        config_paths: &[".vscode/mcp.json", "~/AppData/Roaming/Code/User/mcp.json", "~/Library/Application Support/Code/User/mcp.json", "~/.config/Code/User/mcp.json"],
        config_precedence: &["workspace", "user"],
        native_scopes: &["workspace", "user"],
        supported_ingresses: &["stdio", "streamable-http"],
        documented_features: &["tools", "inputs", "approval"],
        documented_constraints: &["workspace-trust", "servers-root-key"],
        notes: &[
            "VS Code uses a top-level servers object in mcp.json instead of the mcpServers key used by several other clients.",
            "Automatic install uses the platform-specific user mcp.json so one local MCPace endpoint is shared across workspaces; .vscode/mcp.json remains available for manual workspace-only configuration.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "servers",
                url_field: "url",
                include_type_http: true,
                include_tools_star: false,
                include_disabled_false: false,
            }),
            preferred_scope: "user",
            preferred_config_path: "~/.config/Code/User/mcp.json",
        }),
    },
    ClientTarget {
        id: "cursor-local",
        family_id: "cursor",
        display_name: "Cursor local editor and CLI",
        aliases: &["cursor", "cursor-cli", "cursor-editor"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-editor-cli",
        proof_tier: "tier-1",
        config_format: "json",
        config_paths: &["~/.cursor/mcp.json", ".cursor/mcp.json"],
        config_precedence: &["project", "global", "nested"],
        native_scopes: &["project", "global", "nested"],
        supported_ingresses: &["stdio", "streamable-http", "sse"],
        documented_features: &["tools", "oauth"],
        documented_constraints: &["shared-config-cli-editor", "fixed-oauth-callback"],
        notes: &[
            "Cursor CLI uses the same MCP configuration as the editor.",
            "Project config takes precedence over the global file for matching server names.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "mcpServers",
                url_field: "url",
                include_type_http: false,
                include_tools_star: false,
                include_disabled_false: false,
            }),
            preferred_scope: "global",
            preferred_config_path: "~/.cursor/mcp.json",
        }),
    },
    ClientTarget {
        id: "cursor-cloud-agents",
        family_id: "cursor",
        display_name: "Cursor cloud agents",
        aliases: &["cursor-cloud", "cursor-background-agents"],
        maturity: "documented",
        surface_class: "cloud",
        surface_kind: "cloud-agent",
        proof_tier: "catalog-only",
        config_format: "dashboard-or-project",
        config_paths: &[],
        config_precedence: &["project", "team"],
        native_scopes: &["project", "team"],
        supported_ingresses: &["stdio", "streamable-http"],
        documented_features: &["tools", "oauth"],
        documented_constraints: &["cloud-vm", "no-sse", "http-preferred"],
        notes: &[
            "Cloud agents run away from the local workstation, so local-only assumptions do not hold.",
            "HTTP is the safer transport for secrets because the backend can proxy or terminate auth.",
        ],
        install_support: None,
    },
    ClientTarget {
        id: "kiro-ide",
        family_id: "kiro",
        display_name: "Kiro IDE",
        aliases: &["kiro", "kiro-editor"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-ide",
        proof_tier: "tier-2",
        config_format: "json",
        config_paths: &["~/.kiro/settings/mcp.json", ".kiro/settings/mcp.json"],
        config_precedence: &["workspace", "user"],
        native_scopes: &["user", "workspace"],
        supported_ingresses: &["stdio", "streamable-http"],
        documented_features: &["tools"],
        documented_constraints: &["workspace-overrides-user"],
        notes: &[
            "Workspace and user configs merge with workspace precedence.",
            "Local command and remote URL entries share the same JSON file shape.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "mcpServers",
                url_field: "url",
                include_type_http: false,
                include_tools_star: false,
                include_disabled_false: true,
            }),
            preferred_scope: "user",
            preferred_config_path: "~/.kiro/settings/mcp.json",
        }),
    },
    ClientTarget {
        id: "kiro-cli",
        family_id: "kiro",
        display_name: "Kiro CLI",
        aliases: &["kiro-agent", "kirocli"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-cli",
        proof_tier: "tier-2",
        config_format: "json",
        config_paths: &["~/.kiro/settings/mcp.json", ".kiro/settings/mcp.json", "~/.kiro/agents/*.json", "<project>/.kiro/agents/*.json"],
        config_precedence: &["agent", "workspace", "user"],
        native_scopes: &["agent", "workspace", "user"],
        supported_ingresses: &["stdio", "streamable-http", "sse"],
        documented_features: &["tools", "prompts", "oauth"],
        documented_constraints: &["agent-overrides-workspace-user", "tool-name-rules"],
        notes: &[
            "Agent-level config can augment or override MCP from shared settings files.",
            "Tool names and descriptions need to stay within Kiro CLI formatting rules.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "mcpServers",
                url_field: "url",
                include_type_http: false,
                include_tools_star: false,
                include_disabled_false: true,
            }),
            preferred_scope: "user",
            preferred_config_path: "~/.kiro/settings/mcp.json",
        }),
    },
    ClientTarget {
        id: "windsurf",
        family_id: "windsurf",
        display_name: "Windsurf",
        aliases: &["codeium", "windsurf-ide"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-ide",
        proof_tier: "tier-2",
        config_format: "json",
        config_paths: &["~/.codeium/windsurf/mcp_config.json"],
        config_precedence: &["user"],
        native_scopes: &["user"],
        supported_ingresses: &["stdio", "streamable-http", "sse"],
        documented_features: &["tools", "oauth"],
        documented_constraints: &["tool-budget-100"],
        notes: &[
            "Cascade supports stdio, Streamable HTTP, and SSE MCP servers.",
            "The UI enforces a budget of 100 enabled tools across connected MCP servers.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "mcpServers",
                url_field: "serverUrl",
                include_type_http: false,
                include_tools_star: false,
                include_disabled_false: false,
            }),
            preferred_scope: "user",
            preferred_config_path: "~/.codeium/windsurf/mcp_config.json",
        }),
    },
    ClientTarget {
        id: "gemini-cli",
        family_id: "gemini",
        display_name: "Gemini CLI",
        aliases: &["gemini", "google-gemini-cli"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-cli",
        proof_tier: "tier-2",
        config_format: "json",
        config_paths: &["~/.gemini/settings.json", ".gemini/settings.json"],
        config_precedence: &["workspace", "user", "system"],
        native_scopes: &["workspace", "user", "system"],
        supported_ingresses: &["stdio", "streamable-http", "sse"],
        documented_features: &["tools"],
        documented_constraints: &["settings-json"],
        notes: &[
            "User settings live in ~/.gemini/settings.json and project settings live in .gemini/settings.json.",
            "System settings also exist for managed environments, but MCPace currently patches the user settings file.",
            "Transport support is evolving quickly, so compatibility should be proven with real traces.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "mcpServers",
                url_field: "httpUrl",
                include_type_http: false,
                include_tools_star: false,
                include_disabled_false: false,
            }),
            preferred_scope: "user",
            preferred_config_path: "~/.gemini/settings.json",
        }),
    },
    ClientTarget {
        id: "github-copilot-cli",
        family_id: "github-copilot",
        display_name: "GitHub Copilot CLI",
        aliases: &["copilot", "copilot-cli", "github-copilot"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-cli",
        proof_tier: "tier-2",
        config_format: "json",
        config_paths: &["~/.copilot/mcp-config.json"],
        config_precedence: &["session", "user"],
        native_scopes: &["session", "user"],
        supported_ingresses: &["stdio", "streamable-http", "sse"],
        documented_features: &["tools"],
        documented_constraints: &["built-in-github-server", "session-additional-config"],
        notes: &[
            "CLI config can be augmented per session with --additional-mcp-config.",
            "The GitHub MCP server is built in and available without extra configuration.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::JsonMcpServers(JsonMcpServerShape {
                servers_object_key: "mcpServers",
                url_field: "url",
                include_type_http: true,
                include_tools_star: true,
                include_disabled_false: false,
            }),
            preferred_scope: "user",
            preferred_config_path: "~/.copilot/mcp-config.json",
        }),
    },
    ClientTarget {
        id: "github-copilot-cloud-agent",
        family_id: "github-copilot",
        display_name: "GitHub Copilot cloud agent",
        aliases: &["copilot-cloud", "github-copilot-cloud"],
        maturity: "documented",
        surface_class: "cloud",
        surface_kind: "cloud-agent",
        proof_tier: "catalog-only",
        config_format: "repo-json",
        config_paths: &["repository-level MCP config"],
        config_precedence: &["repository"],
        native_scopes: &["repository"],
        supported_ingresses: &["stdio", "streamable-http", "sse"],
        documented_features: &["tools"],
        documented_constraints: &["tools-only", "no-remote-oauth", "no-approval-prompts", "repo-level-config"],
        notes: &[
            "Cloud agent supports tools only; resources and prompts are not available on this surface.",
            "Remote MCP servers that depend on OAuth are not currently supported here.",
        ],
        install_support: None,
    },
    ClientTarget {
        id: "hermes-agent",
        family_id: "hermes",
        display_name: "Hermes Agent",
        aliases: &["hermes", "nous-hermes-agent"],
        maturity: "documented",
        surface_class: "local",
        surface_kind: "local-agent",
        proof_tier: "tier-2",
        config_format: "yaml",
        config_paths: &["~/.hermes/config.yaml", "~/.hermes/.env"],
        config_precedence: &["cli", "config.yaml", ".env", "defaults"],
        native_scopes: &["user"],
        supported_ingresses: &["stdio", "streamable-http"],
        documented_features: &["tools", "resources", "prompts", "oauth"],
        documented_constraints: &["config-yaml-plus-env", "oauth-pkce", "capability-aware-resource-prompt-wrapper"],
        notes: &[
            "Hermes mixes local stdio and remote HTTP MCP servers in one config.",
            "Resources and prompts become utility wrappers only when the server actually exposes those capabilities.",
        ],
        install_support: Some(ClientInstallSupport {
            kind: ClientInstallKind::YamlMcpServersManagedSection,
            preferred_scope: "user",
            preferred_config_path: "~/.hermes/config.yaml",
        }),
    },
    ClientTarget {
        id: "generic-stdio",
        family_id: "generic",
        display_name: "Generic stdio MCP host",
        aliases: &["generic", "stdio"],
        maturity: "generic",
        surface_class: "generic",
        surface_kind: "generic-stdio-host",
        proof_tier: "generic",
        config_format: "host-defined",
        config_paths: &[],
        config_precedence: &["host-defined"],
        native_scopes: &["host-defined"],
        supported_ingresses: &["stdio"],
        documented_features: &[],
        documented_constraints: &["host-defined"],
        notes: &[
            "Use this when the host launches a command and speaks MCP over stdio.",
        ],
        install_support: None,
    },
    ClientTarget {
        id: "generic-http",
        family_id: "generic",
        display_name: "Generic Streamable HTTP MCP host",
        aliases: &["http", "streamable-http"],
        maturity: "generic",
        surface_class: "generic",
        surface_kind: "generic-http-host",
        proof_tier: "generic",
        config_format: "host-defined",
        config_paths: &[],
        config_precedence: &["host-defined"],
        native_scopes: &["host-defined"],
        supported_ingresses: &["streamable-http"],
        documented_features: &[],
        documented_constraints: &["host-defined"],
        notes: &[
            "Use this when the host connects to one MCP URL instead of launching a process.",
        ],
        install_support: None,
    },
    ClientTarget {
        id: "public-http-connector",
        family_id: "generic",
        display_name: "Generic public HTTP MCP connector",
        aliases: &["api-connector", "cloud-http-connector"],
        maturity: "generic",
        surface_class: "cloud",
        surface_kind: "generic-public-http-connector",
        proof_tier: "catalog-only",
        config_format: "request-or-dashboard",
        config_paths: &[],
        config_precedence: &["surface-defined"],
        native_scopes: &["request", "project", "team"],
        supported_ingresses: &["streamable-http", "sse"],
        documented_features: &["tools"],
        documented_constraints: &["tools-only", "public-http-only"],
        notes: &[
            "Use this when the client lives in the cloud and can only reach public HTTP MCP servers.",
        ],
        install_support: None,
    },
];
