#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { inventorySource } from './inventory-source.mjs';
import { deriveProjectName, deriveProjectVersion } from './lib/project-metadata.mjs';
function parseArgs(argv) { const parsed = { json: false, writeJson: null, writeMd: null, top: 25, help: false }; for (let index = 0; index < argv.length; index += 1) { const token = argv[index]; switch (token) { case '--json': parsed.json = true; break; case '--write-json': parsed.writeJson = argv[++index] || null; if (!parsed.writeJson) throw new Error('inventory-project requires a path after --write-json'); break; case '--write-md': parsed.writeMd = argv[++index] || null; if (!parsed.writeMd) throw new Error('inventory-project requires a path after --write-md'); break; case '--top': { const value = Number.parseInt(argv[++index] || '', 10); if (!Number.isFinite(value) || value < 1) throw new Error('inventory-project requires --top >= 1'); parsed.top = value; break; } case '-h': case '--help': parsed.help = true; break; default: throw new Error(`unsupported inventory-project argument: ${token}`); } } return parsed; }
function printHelp() { process.stdout.write('Usage: node scripts/inventory-project.mjs [--json] [--write-json <path>] [--write-md <path>] [--top <n>]\n'); }
function directoryEntries(source) { const map = new Map(); for (const [category, count] of Object.entries(source.byCategory || {})) { const directory = category === 'rust-source' ? 'src' : category; map.set(directory, (map.get(directory) || 0) + count); } return [...map.entries()].map(([directory, files]) => ({ directory, files })).sort((left, right) => right.files - left.files || left.directory.localeCompare(right.directory)); }
export function collectProjectInventory(options = {}) { const source = inventorySource({ top: options.top || 25 }); return { schema: 'mcpace.codeInventory.v2', projectName: deriveProjectName(), version: deriveProjectVersion(), generatedAt: new Date().toISOString(), sourceInventorySchema: source.schema, counts: { totalFiles: source.summary.totalFiles, textFiles: source.summary.textFiles, totalTextLines: source.summary.totalTextLines, rustFiles: source.summary.rustFiles, nodeFiles: source.summary.nodeFiles, markdownFiles: source.summary.markdownFiles, jsonFiles: source.summary.jsonFiles, testFiles: source.summary.testFiles, docsFiles: source.summary.docsFiles, reportsFiles: source.summary.reportsFiles, schemaFiles: source.summary.schemaFiles }, topDirectories: directoryEntries(source), largestRustFiles: source.largestRustModules, largestTextFiles: source.largestTextFiles, versionDrift: source.versions.drift, releaseManifestMissing: source.releaseManifest.missing, presetSummary: source.presets, ok: source.ok, warnings: source.warnings }; }
export function renderInventoryMarkdown(report) { const lines = [`# ${report.projectName} code inventory`,'',`Version: \`${report.version}\``,`Generated: ${report.generatedAt}`,`Status: **${report.ok ? 'ok' : 'attention needed'}**`,'','## Counts','','| metric | value |','|---|---:|']; for (const [key, value] of Object.entries(report.counts)) lines.push(`| ${key} | ${value} |`); lines.push('','## Top directories','','| directory | files |','|---|---:|'); for (const entry of report.topDirectories.slice(0, 20)) lines.push(`| ${entry.directory} | ${entry.files} |`); lines.push('','## Largest Rust files','','| file | lines |','|---|---:|'); for (const entry of report.largestRustFiles.slice(0, 20)) lines.push(`| ${entry.path} | ${entry.lines} |`); if (report.warnings.length > 0) { lines.push('','## Warnings',''); for (const warning of report.warnings) lines.push(`- ${warning}`); } lines.push(''); return `${lines.join('\n')}\n`; }
function writeFileEnsuringDir(relativeOrAbsolutePath, contents) { const target = path.resolve(relativeOrAbsolutePath); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, contents, 'utf8'); }
function isCliInvocation() { const entry = process.argv[1]; return entry ? pathToFileURL(path.resolve(entry)).href === import.meta.url : false; }
function main() { try { const parsed = parseArgs(process.argv.slice(2)); if (parsed.help) { printHelp(); return; } const report = collectProjectInventory(parsed); if (parsed.writeJson) writeFileEnsuringDir(parsed.writeJson, `${JSON.stringify(report, null, 2)}\n`); if (parsed.writeMd) writeFileEnsuringDir(parsed.writeMd, renderInventoryMarkdown(report)); if (parsed.json) process.stdout.write(`${JSON.stringify(report, null, 2)}\n`); else process.stdout.write(`${report.ok ? 'ok' : 'attention needed'}: ${report.counts.totalFiles} files\n`); } catch (error) { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exit(1); } }
if (isCliInvocation()) main();
